---
name: ((deployment-name))

instance_groups:
- azs:
  - z1
  instances: 1
  name: smoke-tests
  networks:
  - name: ((network))
  stemcell: trusty
  vm_type: ((vm_type))
  jobs:
  - name: smoke-tests
    release: cf-rabbitmq-smoke-tests-release
    properties:
      cf:
        api_url: https://api.((system-domain))
        domain: ((system-domain))
        admin_username: ((cf-admin-username))
        admin_password: ((cf-admin-password))
      broker:
        name: ((product-name))
      smoke_tests:
        org: system
  - name: on-demand-broker-smoke-tests
    release: cf-rabbitmq-smoke-tests-release
    properties:
      cf:
        api_url: https://api.((system-domain))
        admin_username: ((cf-admin-username))
        admin_password: ((cf-admin-password))
        org: system
        plans:
          - name: doesnt_matter
        service_offering_name: dummy_offering
      broker:
        name: ((product-name))

releases:
- name: cf-rabbitmq-smoke-tests-release
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: ((stemcell-version))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  max_in_flight: 4
  serial: false
  update_watch_time: 30000-180000
