---
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-golang/go1.25.4.linux-amd64.tar.gz:
  size: 59766394
  object_id: 4b914553-9b5b-4d80-5c01-2383d0abb8ed
  sha: sha256:9fa5ffeda4170de60f67f3aa0f824e426421ba724c21e133c1e35d6159ca1bec
