---
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-golang/go1.25.1.linux-amd64.tar.gz:
  size: 59660846
  object_id: f46ceb32-0817-47ed-6600-b27b13f5e59d
  sha: sha256:7716a0d940a0f6ae8e1f3b3f4f36299dc53e31b16840dbd171254312c41ca12e
