---
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-ginkgo/ginkgo-v1.11.0.tar.gz:
  size: 136779
  object_id: df928050-0a6c-4b32-5e9d-c3a413d3084d
  sha: sha256:f47b16e1b5f2ead3f61891c8d62825553f6520399ebe260afb35d3cb87b49bc1
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-ginkgo/tail-v1.0.0.tar.gz:
  size: 37816
  object_id: a059741c-5ea7-43bc-471e-646aad7e6471
  sha: 1a73f96f30b133ba6255c33490fb4b31ac6c0326
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-golang/go1.13.5.linux-amd64.tar.gz:
  size: 120074076
  object_id: e93fd286-f295-4764-777d-8e054e6dba07
  sha: sha256:512103d7ad296467814a6e3f635631bd35574cab3369a97a323c9a585ccaa569
