---
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-ginkgo/ginkgo-v1.12.0.tar.gz:
  size: 138578
  object_id: 0157bf05-ba54-4acc-4a8b-d55db26d71e7
  sha: sha256:7df557fed1107ac2b8fcbd990336f3f73152cb171f1f1e611df07504001135ff
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-ginkgo/tail-v1.0.0.tar.gz:
  size: 37816
  object_id: a059741c-5ea7-43bc-471e-646aad7e6471
  sha: 1a73f96f30b133ba6255c33490fb4b31ac6c0326
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-golang/go1.13.7.linux-amd64.tar.gz:
  size: 120071076
  object_id: 98e5639d-903b-40c9-6f0e-ae2354a2f77f
  sha: sha256:b3dd4bd781a0271b33168e627f7f43886b4c5d1c794a4015abf34e99c6526ca3
