---
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-golang/go1.25.2.linux-amd64.tar.gz:
  size: 59766306
  object_id: da31b639-9b7d-4799-780c-ae29e60ad3b6
  sha: sha256:d7fa7f8fbd16263aa2501d681b11f972a5fd8e811f7b10cb9b26d031a3d7454b
