---
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-ginkgo/ginkgo-v1.12.0.tar.gz:
  size: 138578
  object_id: 0157bf05-ba54-4acc-4a8b-d55db26d71e7
  sha: sha256:7df557fed1107ac2b8fcbd990336f3f73152cb171f1f1e611df07504001135ff
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-ginkgo/tail-v1.0.0.tar.gz:
  size: 37816
  object_id: a059741c-5ea7-43bc-471e-646aad7e6471
  sha: 1a73f96f30b133ba6255c33490fb4b31ac6c0326
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-golang/go1.14.linux-amd64.tar.gz:
  size: 123550266
  object_id: 3e58af21-d742-46f3-7047-2193cdd38c49
  sha: sha256:08df79b46b0adf498ea9f320a0f23d6ec59e9003660b4c9c1ce8e5e2c6f823ca
