---
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-golang/go1.25.6.linux-amd64.tar.gz:
  size: 59768880
  object_id: b0a4ded5-a5e5-439e-4ffa-9985e7a6ece3
  sha: sha256:f022b6aad78e362bcba9b0b94d09ad58c5a70c6ba3b7582905fababf5fe0181a
