---
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-ginkgo/ginkgo-v1.10.3.tar.gz:
  size: 135716
  object_id: 7063c549-7a32-4840-59e7-1d7d4bed3fb5
  sha: sha256:e0eabdddb99ec380cb8fd492a8bc7557fb5d33832c3ba047e67c0e658f1158a7
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-ginkgo/tail-v1.0.0.tar.gz:
  size: 37816
  object_id: a059741c-5ea7-43bc-471e-646aad7e6471
  sha: 1a73f96f30b133ba6255c33490fb4b31ac6c0326
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-golang/go1.13.3.linux-amd64.tar.gz:
  size: 120055279
  object_id: 867db6bf-e3f6-4d23-4b26-d9ec8acd754d
  sha: sha256:0804bf02020dceaa8a7d7275ee79f7a142f1996bfd0c39216ccb405f93f994c0
