---
# this comment prevents git conflicts
cf-rabbitmq-smoke-tests-golang/go1.25.5.linux-amd64.tar.gz:
  size: 59768009
  object_id: aa1b483a-067a-40c8-4dec-516ae5ef79b6
  sha: sha256:9e9b755d63b36acf30c12a9a3fc379243714c1c6d3dd72861da637f336ebb35b
